[package]
name = "json_errors"
description = "Transforms popular crates' errors into JSON errors. Aimed to be used with Rocket."
license = "MIT"
version = "0.1.4"
authors = ["Thibaut Roche <thibaut.roche.perso@gmail.com>"]
repository = "https://github.com/Aeradriel/rs_json_errors.git"

[dependencies]
rocket = "0.3.15"
rocket_contrib = "0.3.15"
regex = "1.0.1"
serde = "1.0.70"
diesel = { version = "1.3.2", features = ["postgres","r2d2","uuid","chrono"], optional = true }
serde_json = "1.0.22"
serde_derive = "1.0.70"
reqwest = { version = "0.8.6", optional = true }

[features]
diesel-support = ["diesel"]
reqwest-support = ["reqwest"]

[package.metadata.docs.rs]
features = ["diesel_support", "reqwest_support"]
