[package]
name = "diesel_errors"
description = "Diesel error management for rocket apps"
license = "MIT"
version = "0.1.3"
authors = ["Thibaut Roche <thibaut.roche.perso@gmail.com>"]
repository = "https://github.com/Aeradriel/rs_diesel_errors.git"

[dependencies]
rocket = "0.3.15"
rocket_contrib = "0.3.15"
diesel = {version = "1.3.2",features = ["postgres","r2d2","uuid","chrono"]}
regex = "1.0.1"
serde = "1.0.70"
serde_json = "1.0.22"
serde_derive = "1.0.70"
reqwest = "0.8.6"