[package]
name = "json_errors"
description = "Transforms popular crates' errors into JSON errors. Aimed to be used with Rocket."
license = "MIT"
version = "0.2.6"
authors = ["Thibaut Roche <thibaut.roche.perso@gmail.com>"]
repository = "https://github.com/Aeradriel/rs_json_errors.git"
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
regex = "1.1.0"
serde = "1.0.87"
diesel = { version = "1.4.1", features = ["postgres","r2d2","uuid","chrono"], optional = true }
serde_json = "1.0.38"
serde_derive = "1.0.87"
reqwest = { version = "0.9.9", optional = true }

[package.metadata.docs.rs]
features = ["diesel", "reqwest"]
