[package]
name = "json_errors"
description = "Transforms popular crates' errors into JSON errors. Aimed to be used with Rocket."
license = "MIT"
version = "0.2.0"
authors = ["Thibaut Roche <thibaut.roche.perso@gmail.com>"]
repository = "https://github.com/Aeradriel/rs_json_errors.git"

[dependencies]
rocket = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
regex = "1.0.6"
serde = "1.0.80"
diesel = { version = "1.3.3", features = ["postgres","r2d2","uuid","chrono"], optional = true }
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = { version = "0.9.4", optional = true }

[package.metadata.docs.rs]
features = ["diesel", "reqwest"]
